### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by justinr1234** [singer-io/tap-harvest#42]
Today my tap failed on stitchdata with the following log. Nothing has changed on my end, just now it's not working consistently:

```
2021-06-07 19:18:21,988Z   main - INFO Running tap-harvest version 2.0.7 and target-stitch version 3.2.0
2021-06-07 19:18:22,150Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2021-06-07 19:18:22,154Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2021-06-07 19:18:22,155Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2021-06-07 19:18:23,186Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [16] at offset None
2021-06-07 19:18:23,247Z   main - INFO Current state: {"expenses": "2019-11-24T09:47:30.000000Z", "estimate_messages": "2021-04-18T15:18:00.000000Z", "users": "2021-06-06T02:02:19.000000Z", "clients": "2021-05-07T18:06:00.000000Z", "estimates": "2021-04-18T15:18:00.000000Z", "invoice_item_categories": "2019-03-05T19:55:34.000000Z", "project_users": "2021-06-04T18:10:54.000000Z", "time_entries": "2021-06-06T05:41:50.000000Z", "invoices": "2021-06-05T03:06:01.000000Z", "invoice_messages": "2021-06-05T03:06:01.000000Z", "user_projects": "2021-06-04T18:10:54.000000Z", "projects": "2021-05-24T19:43:39.000000Z", "contacts": "2021-05-03T22:05:40.000000Z", "roles": "2021-06-04T18:09:11.000000Z", "expense_categories": "2019-03-05T19:55:33.000000Z", "estimate_item_categories": "2019-03-05T19:55:34.000000Z", "invoice_payments": "2021-06-04T17:39:55.000000Z", "tasks": "2021-05-29T17:42:53.000000Z", "project_tasks": "2021-05-30T12:58:53.000000Z"}
2021-06-07 19:18:23,247Z   main - INFO Starting tap: tap-env/bin/tap-harvest --config /tmp/tap_config.json --state /tmp/tap_state.json
2021-06-07 19:18:23,251Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2021-06-07 19:18:23,547Z    tap - INFO Refreshing access token
2021-06-07 19:18:23,785Z target - INFO Using batch_size_prefernces of {'batch_size_preference': None, 'full_table_streams': [], 'user_batch_size_preference': None}
2021-06-07 19:18:24,326Z    tap - INFO Got refreshed access token
2021-06-07 19:18:24,326Z    tap - INFO Starting sync
2021-06-07 19:18:24,458Z    tap - CRITICAL Expecting value: line 1 column 1 (char 0)
2021-06-07 19:18:24,460Z    tap - Traceback (most recent call last):
2021-06-07 19:18:24,461Z    tap -   File "tap-env/bin/tap-harvest", line 33, in <module>
2021-06-07 19:18:24,461Z    tap -     sys.exit(load_entry_point('tap-harvest==2.0.7', 'console_scripts', 'tap-harvest')())
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 478, in main
2021-06-07 19:18:24,461Z    tap -     raise exc
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 475, in main
2021-06-07 19:18:24,461Z    tap -     main_impl()
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 470, in main_impl
2021-06-07 19:18:24,461Z    tap -     do_sync()
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 418, in do_sync
2021-06-07 19:18:24,461Z    tap -     company = get_company()
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 165, in get_company
2021-06-07 19:18:24,461Z    tap -     return request(url)
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2021-06-07 19:18:24,461Z    tap -     ret = target(*args, **kwargs)
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 51, in wrapper
2021-06-07 19:18:24,461Z    tap -     return func(*args, **kwargs)
2021-06-07 19:18:24,461Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 130, in request
2021-06-07 19:18:24,462Z    tap -     "Harvest-Account-Id": AUTH.get_account_id(),
2021-06-07 19:18:24,462Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_harvest/__init__.py", line 89, in get_account_id
2021-06-07 19:18:24,462Z    tap -     self._account_id = str(response.json()['accounts'][0]['id'])
2021-06-07 19:18:24,462Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 897, in json
2021-06-07 19:18:24,462Z    tap -     return complexjson.loads(self.text, **kwargs)
2021-06-07 19:18:24,462Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
2021-06-07 19:18:24,462Z    tap -     return _default_decoder.decode(s)
2021-06-07 19:18:24,462Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
2021-06-07 19:18:24,462Z    tap -     obj, end = self.raw_decode(s)
2021-06-07 19:18:24,462Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
2021-06-07 19:18:24,462Z    tap -     return self.scan_once(s, idx=_w(s, idx).end())
2021-06-07 19:18:24,462Z    tap - simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-06-07 19:18:24,504Z target - INFO Requests complete, stopping loop
2021-06-07 19:18:24,573Z   main - INFO Target exited normally with status 0
2021-06-07 19:18:25,173Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [41] at offset None
2021-06-07 19:18:25,174Z   main - INFO No tunnel subprocess to tear down
2021-06-07 19:18:25,174Z   main - INFO Exit status is: Tap failed with code 1 and error message: "Expecting value: line 1 column 1 (char 0)". Target succeeded.
```

**Comment by pampy** [comment]
This seems to be fixed in version 2.0.8.
Here's the pull request attached to it: https://github.com/singer-io/tap-harvest/pull/41

From my experience, you'll have the problem that you probably have to wait for Stitchdata to update the embedded version, maybe support can help there?

**Comment by justinr1234** [comment]
@pampy thanks for your help! They’re running that version already. Any other ideas?

**Comment by justinr1234** [comment]
Thanks!
