### ISSUE TITLE
Harvest Integration not successfully extracting data

### ISSUE THREAD

**Issue by Benbentwo** [singer-io/tap-harvest#61]
It appears the Harvest Integration for Stitch has stopped working as of March 2024. The Extraction does not fully error out and stop, however no data is pulled from harvest. Viewing the logs of the extraction you see:

```console
2024-07-10 19:52:10,049Z   main - INFO Running tap-harvest version 2.1.3 and target-stitch version 3.2.1
2024-07-10 19:52:11,194Z   main - INFO No tunnel subprocess to tear down
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.6/bin/stitch-orchestrator", line 33, in <module>
    sys.exit(load_entry_point('stitch-orchestrator==0.80.0', 'console_scripts', 'stitch-orchestrator')())
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/stitch_orchestrator/__init__.py", line 1227, in main
    exit_status = do_sync(tun.connection, menagerie)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/stitch_orchestrator/__init__.py", line 1100, in do_sync
    tap_command = build_tap_command(connection, menagerie)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/stitch_orchestrator/__init__.py", line 735, in build_tap_command
    menagerie.load_state(connection, props)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/stitch_orchestrator/__init__.py", line 428, in load_state
    response = request(self.session, method='get', url=self.get_state_url, timeout=REQUEST_TIMEOUT)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/stitch_orchestrator/__init__.py", line 650, in request
    response.raise_for_status()
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://menagerie.service.stitchdata.com:5033/menagerie/public/v2/clients/<our_id>/connections/<connection_id>/state
```

When trying to re-authorize with harvest we get consistent errors that `we were unable to authorize your account`

![image (1)](https://github.com/singer-io/tap-harvest/assets/14911525/bbc1ce4e-1227-43d4-9cf2-037c5659bbf2)

**Comment by Prasadpisal** [comment]
Hello @Benbentwo ,
Do you found the solution for this error ? I am getting same error, If you know the solution then please tell us.

**Comment by nic-chabot-vooban** [comment]
Same issue here, anyone has a solution?

**Comment by dsprayberry** [comment]
This is an issue specific to the Stitch product. Please raise the issue with Stitch support to inform them of issues with import token expiration. As a workaround, you can create a new connection to Harvest in your Stitch account.
